liip_imagine:
    driver: "gd" # Используем библиотеку GD, она обычно доступна везде

    filter_sets:
        # Название нашего фильтра для маленьких превью
        report_thumbnail:
            quality: 85 # Качество JPEG
            filters:
                # Этот фильтр уменьшает изображение, чтобы оно вписалось в квадрат 300x300
                thumbnail: { size: [300, 300], mode: inset }

        # Название фильтра для большой, но оптимизированной версии
        report_large:
            quality: 80
            filters:
                # Этот фильтр уменьшает изображение по ширине до 1280px, высота подбирается автоматически
                downscale: { max: [1280, 1280] }
