security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_event_index
            logout:
                path: app_logout
                target: app_login

            login_throttling:
                max_attempts: 3
                interval: '5 minutes'

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                signature_properties: ['password', 'updatedAt']

    access_decision_manager:
        strategy: unanimous

    role_hierarchy:
        ROLE_EVENT_VIEW_ANY: [ROLE_EVENT_VIEW]
        ROLE_EVENT_MANAGE_OWN: [ROLE_EVENT_VIEW]
        ROLE_EVENT_MANAGE_ANY: [ROLE_EVENT_MANAGE_OWN, ROLE_EVENT_VIEW_ANY]
        ROLE_EVENT_ADMIN: [ROLE_EVENT_MANAGE_ANY]
        ROLE_EVENT_REPORT_MANAGE: [ROLE_EVENT_REPORT_VIEW]

        ROLE_DEPARTMENT_MANAGE_OWN: [ROLE_DEPARTMENT_VIEW]
        ROLE_DEPARTMENT_MANAGE_ANY: [ROLE_DEPARTMENT_MANAGE_OWN]
        ROLE_DEPARTMENT_ADMIN: [ROLE_DEPARTMENT_MANAGE_ANY]

        ROLE_USER_MANAGE_OWN: [ROLE_USER_VIEW]
        ROLE_USER_VIEW_ALL: [ROLE_USER_VIEW]
        ROLE_USER_MANAGE_ALL: [ROLE_USER_MANAGE_OWN, ROLE_USER_VIEW_ALL]
        ROLE_USER_ADMIN: [ROLE_USER_MANAGE_ALL]

        ROLE_EMPLOYEE_MANAGE_OWN: [ROLE_EMPLOYEE_VIEW]
        ROLE_EMPLOYEE_VIEW_DEPARTMENT: [ROLE_EMPLOYEE_VIEW]
        ROLE_EMPLOYEE_VIEW_ANY: [ROLE_EMPLOYEE_VIEW_DEPARTMENT]
        ROLE_EMPLOYEE_MANAGE_DEPARTMENT: [ROLE_EMPLOYEE_VIEW_DEPARTMENT]
        ROLE_EMPLOYEE_MANAGE_ANY: [ROLE_EMPLOYEE_MANAGE_DEPARTMENT, ROLE_EMPLOYEE_VIEW_ANY]
        ROLE_EMPLOYEE_ADMIN: [ROLE_EMPLOYEE_MANAGE_ANY]

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10