twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        # user_roles: '%app.user_roles%' # Этот глобальный параметр больше не используется

when@test:
    twig:
        strict_variables: true
