vich_uploader:
    db_driver: orm
    mappings:
        report_photos:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        report_scenarios:
            uri_prefix: /uploads/scenarios
            upload_destination: '%kernel.project_dir%/public/uploads/scenarios'
            namer: Vich\UploaderBundle\Naming\UniqidNamer # <-- ИЗМЕНЕНИЕ
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
